baseURL = "http://localhost"
languageCode = 'en'
languageName = "English"
copyright = "© 2020 - 2024 Matt Struble"
title = "Matt Struble"
#paginate = 10
timeout = "60s"

enableRobotsTXT = true
enableGitInfo = true
# theme = "FixIt"

[build]
noJSConfigInAssets = true
[build.buildStats]
# With each build, Hugo writes a hugo_stats.json file that contains arrays
# of the class attributes, id attributes, and tags of each HTML element
# within the published site. For production builds, this file is required
# by PurgeCSS to prune unused CSS.
enable = true

[markup]
[markup.highlight]
# false is a necessary configuration (https://github.com/hugo-fixit/FixIt/issues/43)
noClasses = false
[markup.goldmark]
[markup.goldmark.renderer]
# This setting allows inlining <script> and <style> tags in markdown,
# which is useful and required to use Prism plugins, but may be dangerous
# if the content isn't trustworthy.
unsafe = true

[imaging]
# JPEG and WebP quality
quality = 90

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
# dark or light, defaults to light
defaultTheme = "dark"
themeColor = "blue"
themeContrast = "hard"
subtitle = "AI Software Engineer"
description = "Matt Struble is a AI engineer and computer enthusiast."
toc = true
math = true
enableEmoji = true

# Plausible auth secret to enable public dashboard
# plausibleAuth = "hDl_ZT_txy4BS608-H3Y0"

[params.author]
name = "Matt Struble"
email = ""
link = ""
avatar = ""
[params.footer]
enable = true
since = "2019"
[params.footer.powered]
enable = false
themeLogo = false
[params.footer.siteTime]
enable = true
[params.gitInfo]
repo = "https://github.com/mattstruble/mattstruble.github.io"
branch = "main"
dir = "content"
issueTpl = "title=[BUG]%20{title}&body=|Field|Value|%0A|-|-|%0A|Title|{title}|%0A|URL|{URL}|%0A|Filename|{sourceURL}|"
[params.home]
[params.home.profile]
enable = true
avatarURL = "matt-struble.jpg"
title = "Matt Struble"
subtitle = "I never save anything for the swim back."
[params.search]
enable = true
[params.logo]
text = "struble.dev"
url = "/"

[params.prism]
languages = [
    "markup",
    "css",
    "clike",
    "javascript",
    "bash",
    "hcl",
    "ignore",
    "json",
    "markdown",
    "toml",
    "yaml",
    "python",
    "docker",
]
plugins = [
    "normalize-whitespace",
    "toolbar",
    "copy-to-clipboard",
    "command-line",
]

# Social share links for posts:
#   - iconSuite: "simple-icon" or "tabler-icon"
#   - iconName: name of the icon from the "iconSuite"
#   - {url} placeholder for post .Permalink
#   - {title} placeholder for post .Title
# See  https://github.com/bradvin/social-share-urls for more format strings
[[params.socialShare]]
iconSuite = "simple-icon"
iconName = "x"
formatString = "https://x.com/intent/tweet?url={url}&text={title}"
[[params.socialShare]]
iconSuite = "simple-icon"
iconName = "linkedin"
formatString = "https://www.linkedin.com/sharing/share-offsite/?url={url}"
[[params.socialShare]]
iconSuite = "simple-icon"
iconName = "facebook"
formatString = "https://www.facebook.com/sharer.php?u={url}"
[[params.socialShare]]
iconSuite = "simple-icon"
iconName = "reddit"
formatString = "https://reddit.com/submit?url={url}&title={title}"
[[params.socialShare]]
iconSuite = "simple-icon"
iconName = "ycombinator"
formatString = "https://news.ycombinator.com/submitlink?u={url}&t={title}"
[[params.socialShare]]
iconSuite = "tabler-icon"
iconName = "mail"
formatString = "mailto:?subject={title}&body={url}"

[menu]
[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog"
weight = 10
[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects"
weight = 20
[[menu.main]]
identifier = "about"
name = "About"
url = "/about"
weight = 40
[[menu.main]]
identifier = "cv"
name = "CV"
url = "/cv"
weight = 50
# [[menu.main]]
# identifier = "stats"
# name = "Stats"
# url = "/stats"
# weight = 60

[languages]
[languages.en]
languageName = "English"
weight = 10
[languages.en.params.jsonResume]
present = "present"
