default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: fix-encoding-pragma
      - id: trailing-whitespace # Trim whitespace from end of each line
      - id: end-of-file-fixer # All files only end in newline
      - id: check-yaml # verify yaml syntax
        args: [--allow-multiple-documents]
      - id: check-added-large-files # prevent extremely large files from being committed
        args: [--maxkb=10000]
      - id: mixed-line-ending # force linux line endings
        args: [--fix=lf]
      - id: check-merge-conflict # prevent merge conflict strings
      - id: check-case-conflict # prevent file namings that would fail on case insensitive file systems
      - id: check-toml # validates toml files
      - id: detect-private-key
      - id: check-json

# - repo: https://github.com/stefmolin/exif-stripper
#   rev: 0.5.0
#   hooks:
#     - id: strip-exif
