---
default_stages: [commit]

exclude: "CHANGELOG.md"

repos:
  - repo: https://github.com/shssoichiro/oxipng
    rev: v9.0.0
    hooks:
      - id: oxipng

  - repo: https://github.com/mattstruble/pre-commit-exiftool
    rev: v1.0.0
    hooks:
      - id: strip-exif
