# Site settings
title: Matt Struble
description: >- # this means to ignore newlines until "baseurl:"
  I never save anything for the swim back.
baseurl: ""  # the subpath of your site, e.g. /blog
url: "https://mattstruble.com/" # the base hostname & protocol for your site, e.g. http://example.com
# repository: YoussefRaafatNasry/portfolYOU
remote_theme: YoussefRaafatNasry/portfolYOU

# Build settings
#markdown: kramdown
plugins:
  - jemoji

### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md


# Author Info
author:
  name     : Matt Struble
  image    : /assets/img/profile-image.jpg
  #email    : username@xyz.com
  github   : mattstruble
  twitter  : mestruble
  linkedin : mattstruble


# Collections
collections:
  projects:
    output: true
    permalink: /projects/:title


# Default values for collections
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false


# Posts default Permalink
permalink: blog/:title


# Exclude from processing.
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile.lock