name: Crush Images

on:
  pull_request:
    branches:
      - master
    # paths:
    #   - "**.jpg"
    #   - "**.jpeg"
    #   - "**.png"
    #   - "**.gif"

jobs:
  crush:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Crush Images
        uses: crush-pics/crush-pics-github-action@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          api-key: ${{ secrets.CRUSH_API_KEY }}
